"""
tests/test_signal_bus_doc.py — Freshness gate + determinism + coverage tests for SIGNAL_BUS.md.

(a) Regenerating into a temp file yields EXACTLY the committed bytes — the doc cannot drift
    from the registry.
(b) Determinism: two consecutive generate() calls return identical strings.
(c) All 64 artifact ids appear in the generated content.
(d) Mermaid block is syntactically plausible: balanced backtick fences and starts 'flowchart'.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest
import yaml

# ---------------------------------------------------------------------------
# Locate repo root and import the generator
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SYNAPSE_YML = _REPO_ROOT / "config" / "synapse.yml"
_COMMITTED_DOC = _REPO_ROOT / "docs" / "SIGNAL_BUS.md"

# Import the generator function directly
import importlib.util, sys

_spec = importlib.util.spec_from_file_location(
    "gen_signal_bus_doc",
    _REPO_ROOT / "scripts" / "gen_signal_bus_doc.py",
)
_mod = importlib.util.module_from_spec(_spec)  # type: ignore[arg-type]
_spec.loader.exec_module(_mod)  # type: ignore[union-attr]
generate = _mod.generate


# ---------------------------------------------------------------------------
# (a) Freshness gate — regenerated bytes must match committed doc exactly
# ---------------------------------------------------------------------------


def test_signal_bus_doc_is_fresh():
    """Regenerating docs/SIGNAL_BUS.md must yield byte-for-byte identical content."""
    committed = _COMMITTED_DOC.read_text(encoding="utf-8")
    regenerated = generate(_SYNAPSE_YML)
    assert regenerated == committed, (
        "docs/SIGNAL_BUS.md is out of date with config/synapse.yml.\n"
        "Run: python -m scripts.gen_signal_bus_doc\n"
        f"First diff at char {next(i for i,(a,b) in enumerate(zip(regenerated,committed)) if a!=b) if len(regenerated)==len(committed) else 'lengths differ: {} vs {}'.format(len(regenerated),len(committed))}"
    )


# ---------------------------------------------------------------------------
# (b) Determinism — two runs must be identical
# ---------------------------------------------------------------------------


def test_signal_bus_doc_deterministic():
    """Two consecutive generate() calls must return identical strings."""
    first = generate(_SYNAPSE_YML)
    second = generate(_SYNAPSE_YML)
    assert first == second, "generate() is not deterministic — output differs between calls."


# ---------------------------------------------------------------------------
# (c) All 64 artifact ids appear in the content
# ---------------------------------------------------------------------------


def test_all_artifact_ids_present():
    """Every artifact id registered in synapse.yml must appear in the generated doc."""
    with _SYNAPSE_YML.open(encoding="utf-8") as fh:
        registry = yaml.safe_load(fh)
    artifact_ids = list(registry.get("artifacts", {}).keys())
    assert len(artifact_ids) == 67, (
        f"Expected 67 artifacts in synapse.yml, found {len(artifact_ids)}. "
        "Update the test if the registry count changed intentionally."
    )
    content = generate(_SYNAPSE_YML)
    missing = [aid for aid in artifact_ids if aid not in content]
    assert not missing, (
        f"The following artifact ids are missing from SIGNAL_BUS.md: {missing}"
    )


# ---------------------------------------------------------------------------
# (d) Mermaid block is syntactically plausible
# ---------------------------------------------------------------------------


def test_mermaid_block_plausible():
    """Mermaid code block must be balanced (open+close) and start with 'flowchart'."""
    content = generate(_SYNAPSE_YML)

    # Find all ```mermaid ... ``` blocks
    blocks = re.findall(r"```mermaid\n(.*?)```", content, re.DOTALL)
    assert blocks, "No ```mermaid``` block found in SIGNAL_BUS.md"

    for i, block in enumerate(blocks):
        stripped = block.strip()
        assert stripped.startswith("flowchart"), (
            f"Mermaid block {i} does not start with 'flowchart':\n{stripped[:120]}"
        )
        # Must have at least one edge line (-->)
        assert "-->" in stripped, (
            f"Mermaid block {i} contains no edges (-->):\n{stripped[:300]}"
        )

    # Verify backtick fences are balanced in the full document
    fence_count = content.count("```")
    assert fence_count % 2 == 0, (
        f"Odd number of backtick fences in SIGNAL_BUS.md ({fence_count}); "
        "at least one code block is unclosed."
    )
