"""
tests/test_signal_bus_doc.py — Freshness gate + determinism + coverage tests for SIGNAL_BUS.md.

(a) Regenerating into a temp file yields EXACTLY the committed bytes — the doc cannot drift
    from the registry.
(b) Determinism: two consecutive generate() calls return identical strings.
(c) All 100 artifact ids appear in the generated content.
(d) Mermaid block is syntactically plausible: balanced backtick fences and starts 'flowchart'.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest
import yaml

# ---------------------------------------------------------------------------
# Locate repo root and import the generator
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SYNAPSE_YML = _REPO_ROOT / "config" / "synapse.yml"
_COMMITTED_DOC = _REPO_ROOT / "docs" / "SIGNAL_BUS.md"

# Import the generator function directly
import importlib.util, sys

_spec = importlib.util.spec_from_file_location(
    "gen_signal_bus_doc",
    _REPO_ROOT / "scripts" / "gen_signal_bus_doc.py",
)
_mod = importlib.util.module_from_spec(_spec)  # type: ignore[arg-type]
_spec.loader.exec_module(_mod)  # type: ignore[union-attr]
generate = _mod.generate


# ---------------------------------------------------------------------------
# (a) Freshness gate — regenerated bytes must match committed doc exactly
# ---------------------------------------------------------------------------


def test_signal_bus_doc_is_fresh():
    """Regenerating docs/SIGNAL_BUS.md must yield byte-for-byte identical content."""
    committed = _COMMITTED_DOC.read_text(encoding="utf-8")
    regenerated = generate(_SYNAPSE_YML)
    assert regenerated == committed, (
        "docs/SIGNAL_BUS.md is out of date with config/synapse.yml.\n"
        "Run: python -m scripts.gen_signal_bus_doc\n"
        f"First diff at char {next(i for i,(a,b) in enumerate(zip(regenerated,committed)) if a!=b) if len(regenerated)==len(committed) else 'lengths differ: {} vs {}'.format(len(regenerated),len(committed))}"
    )


# ---------------------------------------------------------------------------
# (b) Determinism — two runs must be identical
# ---------------------------------------------------------------------------


def test_signal_bus_doc_deterministic():
    """Two consecutive generate() calls must return identical strings."""
    first = generate(_SYNAPSE_YML)
    second = generate(_SYNAPSE_YML)
    assert first == second, "generate() is not deterministic — output differs between calls."


# ---------------------------------------------------------------------------
# (c) All artifact ids appear in the content
# ---------------------------------------------------------------------------


def test_all_artifact_ids_present():
    """Every artifact id registered in synapse.yml must appear in the generated doc."""
    with _SYNAPSE_YML.open(encoding="utf-8") as fh:
        registry = yaml.safe_load(fh)
    artifact_ids = list(registry.get("artifacts", {}).keys())
    assert len(artifact_ids) == 226, (
        f"Expected 226 artifacts in synapse.yml, found {len(artifact_ids)}. "
        "Update the test if the registry count changed intentionally."
        " (B6 watchlist sentinel added watchlist-alerts-jsonl, watchlist-sentinel-states,"
        " watchlist-sentinel-cooldown = 223->226;"
        " W7b added machine-registry, cortex-attention-grades, cortex-probation = 104->107;"
        " W6b added ops-push-basket-freeze, ops-push-signal-sanity, ops-push-healthcheck = 107->110;"
        " signal bus registry now carries 112 artifacts;"
        " W3 event-intelligence added 6 event-priors artifacts = 112->118;"
        " Signal Commons W2 added kernel-half-lives = 118->119;"
        " entry-stack B0-1 added bottom-sensors-json, bottom-sensors-parquet = 119->121;"
        " options-nw W-A added options-entry-state, options-entry-gate, options-skew-snapshots,"
        " options-ivspread-snapshots, live-options-flow-current = 121->126;"
        " nwqs-B added research-queue = 126->127;"
        " gex-nerve added gex-state-history = 127->128;"
        " oracle reversion promo P0+P1 added oracle-reversion-forward-ledger, oracle-reversion-state = 128->130;"
        " long-hold W1 PR-E added long-hold-labels, long-hold-labels-manifest = 130->132;"
        " long-hold W1 dead-name build added long-hold-dead-name-prices = 132->133;"
        " OTA W6 turn desk added oracle-turn-desk, oracle-turn-desk-ledger = 133->135;"
        " long-hold W1 PR-F killtest added long-hold-killtest-results = 135->136;"
        " NW-rails PR-4 added dispersion-regime = 136->137;"
        " long-hold W2 PR-J two clocks added long-hold-clocks = 137->138;"
        " NW-rails PR-1 added rule-experiment-registry, rule-experiment-summaries = 141->143;"
        " NW-rails PR-6 added grading-closure = 143->144;"
        " long-hold W2 PR-I added long-hold-compounder-features = 144->145;"
        " long-hold W2 PR-K added moat-falsifier-sensors, great-company-trap = 145->147;"
        " NW-rails PR-8 added operator-action-ledger = 147->148;"
        " nw-mastermind-bridge W1 added kernel-decisions, neuralweb-mastermind-context,"
        " site-neuralweb-mastermind-context = 148->151;"
        " OTA W7 qualitative fusion added oracle-qual-filter-registry, oracle-qual-filter-stamps,"
        " oracle-qual-filter-accrual = 151->154;"
        " research-factory W1 added research-factory-candidates, research-factory-transitions,"
        " research-factory-paper-monitor = 154->157;"
        " factor-intel NW W1 added factor-intelligence-state, site-factor-intelligence-state,"
        " factor-state-history, fire-coordinates, factor-contradictions-ledger = 157->162;"
        " long-hold LT-2a added long-hold-expect-drift-manifest, long-hold-expect-drift-panel = 162->164;"
        " insider-LH panel build added insider-lh-panel, insider-lh-panel-manifest,"
        " insider-lh-ruler-p-results = 164->167;"
        " long-hold LT-3a added capital-allocation-delta = 167->168;"
        " SRSS Phase 2 added subsector-sponsorship-spine = 168->169;"
        " long-hold LT-2b added expect-drift-ruler-p-results = 169->170;"
        " long-hold LT-2c added long-hold-expectation-state = 170->171;"
        " PR-C nw-health added neuralweb-health, site-neuralweb-health = 171->173;"
        " china-intel W2 added site-china-special-sits = 173->174;"
        " SRSS revert (#1479 merged in race despite BLOCK-superseded review; §C3"
        " sponsorship_state in bottom_sensors.py is canonical) removed"
        " subsector-sponsorship-spine = 174->173;"
        " PR-D nw-daily-brief added neuralweb-daily-brief, site-neuralweb-daily-brief,"
        " neuralweb-daily-brief-history = 173->176;"
        " long-hold LT-1c added ticker-sectors = 176->177;"
        " (pin drifted: registry carried 180 while pin said 177 — racing merges; repaired here);"
        " CPI substrate v0 added cycle-pattern-entities, cycle-pattern-state-monthly,"
        " cycle-pattern-outcomes, cycle-pattern-truths, signal-archive-context-daily = 180->185;"
        " CPI P2 state_daily_live adapter added cycle-pattern-state-daily-live = 185->186;"
        " china-intel W4 added site-china-intel-command = 186->187;"
        " NW next-lobes DQ-2 operator-action grading harness added operator-grading = 187->188;"
        " short-side BD-AVOID-1 Phase-1 added bd-avoid1-ledger = 188->189;"
        " NEXT3 W-EX added operator-exposure-log, operator-exposure-summary = 189->191;"
        " (pin drifted: registry carried 198 while pin said 191 — racing merges; repaired here);"
        " DT-NW-1 added dt-contra-state = 198->199;"
        " R-ORTH PR-3 added covariance-spine, site-covariance-spine, covariance-spine-history = 199->202;"
        " CPI netliq artifact added fed-net-liquidity = 202->203;"
        " CPI IX-1 substrate added hazard-panel-index-v0 = 203->204;"
        " CPI P-D5-1 phase 4a added regime-v2-pit = 204->205;"
        " (pin drifted: registry carried 210 while pin said 205 — racing merges"
        " during the 2026-07-06 CPI wave train; repaired here);"
        " CPI P6 wave 1 added cycle-pattern-state = 210->211;"
        " active-build-map added active-builds = 211->212;"
        " feedback-contract W2 added site-mastermind-nw-feedback, mastermind-feedback-summary = 212->214;"
        " Ruling Graph v1 added site-neuralweb-ruling-graph = 214->215;"
        " ETM added entity-thesis-mechanism-registry = 215->216;"
        " evidence-clock PR-1 added evidence-clock, evidence-clock-reviews = 216->218;"
        " codex-docket event-landmine added event-windows = 218->219;"
        " NW core-cognition W1 added mechanism-pathways, mechanism-pathways-history, site-mechanism-pathways = 219->222;"
        " nasdaq-internals program added nasdaq-internals = 222->223;"
        " B6 watchlist sentinel added watchlist-alerts-jsonl, watchlist-sentinel-states,"
        " watchlist-sentinel-cooldown = 223->226)"
    )
    content = generate(_SYNAPSE_YML)
    missing = [aid for aid in artifact_ids if aid not in content]
    assert not missing, (
        f"The following artifact ids are missing from SIGNAL_BUS.md: {missing}"
    )


# ---------------------------------------------------------------------------
# (d) Mermaid block is syntactically plausible
# ---------------------------------------------------------------------------


def test_mermaid_block_plausible():
    """Mermaid code block must be balanced (open+close) and start with 'flowchart'."""
    content = generate(_SYNAPSE_YML)

    # Find all ```mermaid ... ``` blocks
    blocks = re.findall(r"```mermaid\n(.*?)```", content, re.DOTALL)
    assert blocks, "No ```mermaid``` block found in SIGNAL_BUS.md"

    for i, block in enumerate(blocks):
        stripped = block.strip()
        assert stripped.startswith("flowchart"), (
            f"Mermaid block {i} does not start with 'flowchart':\n{stripped[:120]}"
        )
        # Must have at least one edge line (-->)
        assert "-->" in stripped, (
            f"Mermaid block {i} contains no edges (-->):\n{stripped[:300]}"
        )

    # Verify backtick fences are balanced in the full document
    fence_count = content.count("```")
    assert fence_count % 2 == 0, (
        f"Odd number of backtick fences in SIGNAL_BUS.md ({fence_count}); "
        "at least one code block is unclosed."
    )
