"""Shared sector-intelligence contract validation primitives."""

from .contracts import (
    ContractError,
    ContractRegistry,
    ContractRegistryError,
    ContractValidationError,
    UnsupportedContractError,
    ValidationIssue,
    canonical_json_bytes,
    canonical_json_sha256,
    ctgov_query_manifest_sha256,
    discover_contract_schemas,
    exact_json_diff,
    receipt_payloads_sha256,
    validate_contract,
    validate_ctgov_fetch_run_against_receipts,
    validate_evidence_claim_against_source_records,
    validate_trial_observation_against_source_evidence,
    validate_trial_source_snapshot_against_fetch_evidence,
    validate_trial_diff_against_snapshots,
    validate_trial_projection_against_source,
)

__all__ = [
    "ContractError",
    "ContractRegistry",
    "ContractRegistryError",
    "ContractValidationError",
    "UnsupportedContractError",
    "ValidationIssue",
    "canonical_json_bytes",
    "canonical_json_sha256",
    "ctgov_query_manifest_sha256",
    "discover_contract_schemas",
    "exact_json_diff",
    "receipt_payloads_sha256",
    "validate_contract",
    "validate_ctgov_fetch_run_against_receipts",
    "validate_evidence_claim_against_source_records",
    "validate_trial_observation_against_source_evidence",
    "validate_trial_source_snapshot_against_fetch_evidence",
    "validate_trial_diff_against_snapshots",
    "validate_trial_projection_against_source",
]
