"""One-shot full rebuild of limit_tape.parquet + limit_events.parquet from 2011 to latest.

Reads every current data/china_stocks_raw/*.parquet file (raw nominal OHLCV) and produces:
  data/china_microstructure/limit_tape.parquet   — market-day aggregates (full depth 2011→)
  data/china_microstructure/limit_events.parquet — event rows (full depth 2011→)
  data/china_microstructure/completeness_manifest.json — reproducible input/output receipt

Publication contract
--------------------
Every discovered nominal file must be readable. The two parquet artifacts are written to
same-directory temporary files and individually replaced atomically; the manifest is replaced
last and acts as the generation commit marker. A partial ``--start`` run is dry-run only and
can never overwrite the complete stores.

Start-date floor
----------------
The §5 frozen contract mandates "2011→" data.  Regardless of --start, no bars before
2011-01-01 enter detection or aggregation.  This prevents fabricated limit-events from the
pre-1997 no-limit regime (China's ±10% daily price limit was introduced in Dec-1996; applying
the rule to 1990-1996 data produces structural artefacts, not real events).

Sanity gates (must PASS or the script aborts with a non-zero exit):
  1. 2015-06..07 shows elevated limit-down/sealed_down clusters vs adjacent months.
  2. 2014-11..12 shows elevated sealed_up counts vs adjacent months.
  3. Nonzero events in every year 2012→.
  4. min(tape.date) >= 2011-01-01 (no pre-floor rows).

Usage
-----
  python scripts/backfill_china_limit_tape.py
  python3 scripts/backfill_china_limit_tape.py --start 2015-01-01 --dry-run
  python scripts/backfill_china_limit_tape.py --dry-run             # stop before write
  python3 scripts/backfill_china_limit_tape.py --check-manifest
  python3 scripts/backfill_china_limit_tape.py --comparison-ref <prior-generation-commit>

The script is idempotent: if the stores already exist they are replaced with the fresh run.
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import logging
import os
import subprocess
import sys
import uuid
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd
import pyarrow

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

log = logging.getLogger("backfill_china_limit_tape")
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

RAW_DIR     = ROOT / "data" / "china_stocks_raw"
OUT_DIR     = ROOT / "data" / "china_microstructure"
TAPE_PATH   = OUT_DIR / "limit_tape.parquet"
EVENTS_PATH = OUT_DIR / "limit_events.parquet"
MANIFEST_PATH = OUT_DIR / "completeness_manifest.json"
MANIFEST_SCHEMA_VERSION = "china_microstructure.completeness.v2"
REBUILD_IMPLEMENTATION_VERSION = "full-rebuild-v3"
PINNED_PYTHON = "/opt/homebrew/Caskroom/miniconda/base/bin/python"
ORIGINAL_RAW_UNIVERSE_COUNT = 1_587
REFERENCE_TICKER = "600519.SS"
ORIGINAL_UNIVERSE_GIT_REF = "aa3a75128f49a0a3725ecdfa56902295ca648a70"
PRE_REBUILD_COMPARISON_REF = "e1fea822972e359a73dedfa34b6c4e03a192b255"
REGISTRATION_ONLY_COMPARISON_REF = "8979887ec7dd63f610efcaa4e5f491ef1c827ca8"
GAP_CENSUS_CUTOFF = pd.Timestamp("2026-06-30")
MARKET_CLOCK_SUPPORT_MIN = 50
MARKET_CLOCK_PIN_MAX_DATE = pd.Timestamp("2026-08-07")
MARKET_CLOCK_PIN_SESSION_COUNT = 3_786
MARKET_CLOCK_PIN_DATE = pd.Timestamp("2014-12-25")
MARKET_CLOCK_PIN_DATE_SUPPORT = 894


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def raw_universe_inventory(
    raw_dir: Path = RAW_DIR,
    *,
    include_content_hash: bool = False,
) -> tuple[list[Path], dict[str, Any]]:
    """Return sorted raw files and a deterministic inventory receipt.

    ``membership_sha256`` hashes relative filenames and is intentionally cheap enough for a
    nightly/CI drift sentinel. ``content_sha256`` additionally binds every source byte and is
    generated by full rebuilds only.
    """
    files = sorted(raw_dir.glob("*.parquet"), key=lambda path: path.name)
    names_payload = "".join(f"{path.name}\n" for path in files).encode("utf-8")
    inventory: dict[str, Any] = {
        "file_count": len(files),
        "membership_sha256": hashlib.sha256(names_payload).hexdigest(),
    }
    if include_content_hash:
        content_digest = hashlib.sha256()
        for path in files:
            content_digest.update(path.name.encode("utf-8"))
            content_digest.update(b"\0")
            content_digest.update(bytes.fromhex(_sha256_file(path)))
        inventory["content_sha256"] = content_digest.hexdigest()
    return files, inventory


def _observed_market_session_clock(
    raw_files: list[Path],
    *,
    floor: pd.Timestamp,
) -> tuple[dict[pd.Timestamp, int], dict[str, Any]]:
    """Build a consensus calendar and validate it against an unfiltered reference index."""
    support: Counter[pd.Timestamp] = Counter()
    contributing_files = 0
    for path in raw_files:
        try:
            volume_frame = pd.read_parquet(path, columns=["volume"])
        except Exception as exc:  # noqa: BLE001
            raise RuntimeError(
                f"market-session clock incomplete: cannot read {path.name}: {exc}"
            ) from exc
        index = pd.DatetimeIndex(pd.to_datetime(volume_frame.index, errors="coerce"))
        volume = pd.to_numeric(volume_frame["volume"], errors="coerce").to_numpy()
        eligible = [
            pd.Timestamp(ts).normalize()
            for ts, value in zip(index, volume, strict=True)
            if not pd.isna(ts)
            and pd.Timestamp(ts).normalize() >= floor
            and pd.notna(value)
            and float(value) > 0
        ]
        if eligible:
            contributing_files += 1
            support.update(set(eligible))

    consensus_dates = {
        date for date, count in support.items() if count >= MARKET_CLOCK_SUPPORT_MIN
    }
    reference_path = RAW_DIR / f"{REFERENCE_TICKER}.parquet"
    try:
        reference = pd.read_parquet(reference_path, columns=["volume"])
    except Exception as exc:  # noqa: BLE001
        raise RuntimeError(
            f"market-session clock reference unreadable: {reference_path.name}: {exc}"
        ) from exc
    reference_index = pd.DatetimeIndex(pd.to_datetime(reference.index, errors="coerce"))
    reference_dates = {
        pd.Timestamp(ts).normalize()
        for ts in reference_index
        if not pd.isna(ts) and pd.Timestamp(ts).normalize() >= floor
    }
    if consensus_dates != reference_dates:
        consensus_only = sorted(consensus_dates - reference_dates)
        reference_only = sorted(reference_dates - consensus_dates)
        raise RuntimeError(
            "market-session clock consensus/reference mismatch: "
            f"consensus_only={len(consensus_only)} {consensus_only[:10]!r}; "
            f"reference_only={len(reference_only)} {reference_only[:10]!r}"
        )

    ordered = sorted(consensus_dates)
    current_pin_applies = bool(ordered and ordered[-1] == MARKET_CLOCK_PIN_MAX_DATE)
    pin_support = int(support[MARKET_CLOCK_PIN_DATE])
    if current_pin_applies and (
        len(ordered) != MARKET_CLOCK_PIN_SESSION_COUNT
        or pin_support != MARKET_CLOCK_PIN_DATE_SUPPORT
    ):
        raise RuntimeError(
            "market-session clock current-generation pin drift: "
            f"sessions={len(ordered)} expected={MARKET_CLOCK_PIN_SESSION_COUNT}; "
            f"{MARKET_CLOCK_PIN_DATE.date()} support={pin_support} "
            f"expected={MARKET_CLOCK_PIN_DATE_SUPPORT}"
        )
    payload = "".join(f"{date.strftime('%Y-%m-%d')}\n" for date in ordered).encode("utf-8")
    positions = {date: position for position, date in enumerate(ordered)}
    receipt = {
        "method": (
            "dates_with_at_least_50_positive_volume_names_validated_equal_to_"
            "unfiltered_600519.SS_index"
        ),
        "floor": floor.strftime("%Y-%m-%d"),
        "sessions": len(ordered),
        "min_date": ordered[0].strftime("%Y-%m-%d") if ordered else None,
        "max_date": ordered[-1].strftime("%Y-%m-%d") if ordered else None,
        "sha256": hashlib.sha256(payload).hexdigest(),
        "files_scanned": len(raw_files),
        "files_contributing": contributing_files,
        "support_minimum_names": MARKET_CLOCK_SUPPORT_MIN,
        "reference_ticker": REFERENCE_TICKER,
        "reference_volume_filter_applied": False,
        "consensus_reference_exact_set_match": True,
        "generation_pin": {
            "applied": current_pin_applies,
            "max_date": MARKET_CLOCK_PIN_MAX_DATE.strftime("%Y-%m-%d"),
            "sessions": MARKET_CLOCK_PIN_SESSION_COUNT,
            "support_date": MARKET_CLOCK_PIN_DATE.strftime("%Y-%m-%d"),
            "support_names": pin_support,
            "expected_support_names": MARKET_CLOCK_PIN_DATE_SUPPORT,
        },
        "lianban_requires_adjacent_clock_positions": True,
        "missing_or_unattested_clock_behavior": "fail_closed_reset_streak",
    }
    return positions, receipt


def _lianban_session_clock_audit(
    events: pd.DataFrame,
    market_session_positions: dict[pd.Timestamp, int],
) -> dict[str, Any]:
    """Recompute every sealed-up streak from event dates and the market clock."""
    sealed = events.loc[events["event"].eq("sealed_up")].copy()
    if sealed.empty:
        return {
            "sealed_up_rows": 0,
            "reported_lianban_2plus": 0,
            "recomputed_lianban_2plus": 0,
            "attribute_mismatches": 0,
            "false_gap_bridges": 0,
            "mismatch_examples": [],
        }
    sealed["date"] = pd.to_datetime(sealed["date"]).dt.normalize()
    sealed = sealed.sort_values(["ticker", "date"])
    mismatches: list[dict[str, Any]] = []
    mismatch_count = 0
    recomputed_2plus = 0
    false_gap_bridges = 0
    for ticker, rows in sealed.groupby("ticker", sort=False):
        previous_date: pd.Timestamp | None = None
        streak = 0
        for row in rows.itertuples(index=False):
            trade_date = pd.Timestamp(row.date).normalize()
            previous_position = market_session_positions.get(previous_date)
            current_position = market_session_positions.get(trade_date)
            adjacent = (
                previous_position is not None
                and current_position is not None
                and current_position == previous_position + 1
            )
            streak = streak + 1 if adjacent else 1
            reported = int(row.lianban_count)
            if streak >= 2:
                recomputed_2plus += 1
            if reported != streak:
                mismatch_count += 1
                if reported >= 2 and streak == 1:
                    false_gap_bridges += 1
                if len(mismatches) < 25:
                    mismatches.append({
                        "ticker": str(ticker),
                        "date": trade_date.strftime("%Y-%m-%d"),
                        "previous_sealed_up_date": (
                            previous_date.strftime("%Y-%m-%d")
                            if previous_date is not None
                            else None
                        ),
                        "reported": reported,
                        "recomputed": streak,
                    })
            previous_date = trade_date
    return {
        "sealed_up_rows": len(sealed),
        "reported_lianban_2plus": int(sealed["lianban_count"].ge(2).sum()),
        "recomputed_lianban_2plus": recomputed_2plus,
        "attribute_mismatches": mismatch_count,
        "false_gap_bridges": false_gap_bridges,
        "mismatch_examples": mismatches,
    }


def _build_identity_payload(manifest: dict[str, Any]) -> dict[str, Any]:
    """Return the canonical provenance payload bound by ``build_identity``."""
    return {
        "schema_version": manifest["schema_version"],
        "implementation_version": manifest["implementation_version"],
        "producer_sources": manifest["producer"]["source_sha256"],
        "raw_universe": manifest["raw_universe"],
        "rule_era": manifest["rule_era"],
        "market_session_clock": manifest["market_session_clock"],
        "st_membership": manifest["st_membership"],
        "prior_vs_rebuilt_reconciliation": manifest["prior_vs_rebuilt_reconciliation"],
        "rule_fix_vs_registration_only_generation": manifest[
            "rule_fix_vs_registration_only_generation"
        ],
        "artifacts": manifest["artifacts"],
    }


def _build_identity_value(manifest: dict[str, Any]) -> str:
    canonical = json.dumps(
        _build_identity_payload(manifest),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
    ).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest()


def validate_completeness_manifest(
    manifest_path: Path = MANIFEST_PATH,
    raw_dir: Path = RAW_DIR,
) -> list[str]:
    """Return manifest/universe drift defects; an empty list means the sentinel passes."""
    if not manifest_path.exists():
        return [f"completeness manifest missing: {manifest_path}"]
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001
        return [f"completeness manifest unreadable: {exc}"]

    defects: list[str] = []
    if manifest.get("schema_version") != MANIFEST_SCHEMA_VERSION:
        defects.append(
            f"manifest schema mismatch: {manifest.get('schema_version')!r} "
            f"!= {MANIFEST_SCHEMA_VERSION!r}"
        )
    if manifest.get("complete") is not True:
        defects.append("manifest does not attest complete=true")

    _, current = raw_universe_inventory(raw_dir, include_content_hash=True)
    recorded = manifest.get("raw_universe", {})
    for key in ("file_count", "membership_sha256", "content_sha256"):
        if recorded.get(key) != current[key]:
            defects.append(
                f"raw universe {key} drift: manifest={recorded.get(key)!r} "
                f"current={current[key]!r}"
            )
    scan = manifest.get("scan", {})
    if scan.get("unreadable_count") != 0 or scan.get("unreadable_files"):
        defects.append("manifest reports unreadable raw files")
    if scan.get("files_scanned") != recorded.get("file_count"):
        defects.append("manifest scanned-file count does not cover the recorded universe")

    manifest_root = ROOT if manifest_path.resolve() == MANIFEST_PATH.resolve() else manifest_path.parent
    artifacts = manifest.get("artifacts", {})
    for name in ("limit_events", "limit_tape"):
        receipt = artifacts.get(name, {})
        receipt_path = receipt.get("path")
        expected = receipt.get("sha256")
        if not receipt_path or not expected:
            defects.append(f"manifest artifact receipt missing: {name}")
            continue
        path = Path(receipt_path)
        if not path.is_absolute():
            path = manifest_root / path
        if not path.exists():
            defects.append(f"manifest artifact missing: {path}")
        elif _sha256_file(path) != expected:
            defects.append(f"manifest artifact sha256 drift: {name}")

    producer_sources = manifest.get("producer", {}).get("source_sha256", {})
    for relative_path, expected in producer_sources.items():
        path = Path(relative_path)
        if not path.is_absolute():
            path = manifest_root / path
        if not path.exists():
            defects.append(f"manifest producer source missing: {relative_path}")
        elif _sha256_file(path) != expected:
            defects.append(f"manifest producer source sha256 drift: {relative_path}")
    if not producer_sources:
        defects.append("manifest producer source hashes missing")

    identity = manifest.get("build_identity", {})
    if not identity.get("value"):
        defects.append("manifest build identity missing")
    else:
        try:
            actual_identity = _build_identity_value(manifest)
        except (KeyError, TypeError, ValueError) as exc:
            defects.append(f"manifest build identity inputs incomplete: {exc}")
        else:
            if identity["value"] != actual_identity:
                defects.append("manifest build identity drift")
    return defects


def _git_bytes(ref: str, relative_path: str) -> bytes:
    return subprocess.check_output(
        ["git", "show", f"{ref}:{relative_path}"],
        cwd=ROOT,
    )


def _git_blob(ref: str, relative_path: str) -> str:
    return subprocess.check_output(
        ["git", "rev-parse", f"{ref}:{relative_path}"],
        cwd=ROOT,
        text=True,
    ).strip()


def _baseline_universe_tickers() -> set[str]:
    paths = subprocess.check_output(
        [
            "git", "ls-tree", "-r", "--name-only", ORIGINAL_UNIVERSE_GIT_REF,
            "--", "data/china_stocks_raw",
        ],
        cwd=ROOT,
        text=True,
    ).splitlines()
    return {
        Path(path).stem
        for path in paths
        if path.endswith(".parquet")
    }


def _load_comparison_artifacts(
    comparison_ref: str | None,
) -> tuple[pd.DataFrame, set[str], dict[str, Any]]:
    """Load the exact pre-rebuild events/tape generation for a deterministic diff."""
    paths = {
        "events": "data/china_microstructure/limit_events.parquet",
        "tape": "data/china_microstructure/limit_tape.parquet",
    }
    if comparison_ref:
        events = pd.read_parquet(io.BytesIO(_git_bytes(comparison_ref, paths["events"])))
        tape = pd.read_parquet(io.BytesIO(_git_bytes(comparison_ref, paths["tape"])))
        source = {
            "kind": "git_ref",
            "ref": comparison_ref,
            "event_blob": _git_blob(comparison_ref, paths["events"]),
            "tape_blob": _git_blob(comparison_ref, paths["tape"]),
        }
    else:
        events = pd.read_parquet(EVENTS_PATH) if EVENTS_PATH.exists() else pd.DataFrame()
        tape = pd.read_parquet(TAPE_PATH) if TAPE_PATH.exists() else pd.DataFrame()
        source = {
            "kind": "preexisting_worktree_artifacts",
            "event_sha256": _sha256_file(EVENTS_PATH) if EVENTS_PATH.exists() else None,
            "tape_sha256": _sha256_file(TAPE_PATH) if TAPE_PATH.exists() else None,
        }
    tape_dates = (
        set(pd.to_datetime(tape["date"]).dt.strftime("%Y-%m-%d"))
        if not tape.empty and "date" in tape
        else set()
    )
    return events, tape_dates, source


def _event_slice_summary(frame: pd.DataFrame) -> dict[str, Any]:
    if frame.empty:
        return {"rows": 0, "tickers": 0, "by_ticker": {}, "by_event": {}, "by_year": {}}
    return {
        "rows": int(len(frame)),
        "tickers": int(frame["ticker"].nunique()),
        "by_ticker": {
            str(key): int(value)
            for key, value in frame["ticker"].value_counts().sort_index().items()
        },
        "by_event": {
            str(key): int(value)
            for key, value in frame["event"].value_counts().sort_index().items()
        },
        "by_year": {
            str(key): int(value)
            for key, value in frame["date"].dt.year.value_counts().sort_index().items()
        },
    }


def _raw_revision_evidence(tickers: set[str]) -> dict[str, Any]:
    """Count overlapping OHLCV bars changed since the original 1,587-file generation."""
    evidence: dict[str, Any] = {}
    for ticker in sorted(tickers):
        relpath = f"data/china_stocks_raw/{ticker}.parquet"
        old = pd.read_parquet(io.BytesIO(_git_bytes(ORIGINAL_UNIVERSE_GIT_REF, relpath)))
        current = pd.read_parquet(ROOT / relpath)
        old.index = pd.to_datetime(old.index)
        current.index = pd.to_datetime(current.index)
        common = old.index.intersection(current.index)
        columns = [
            col for col in ("open", "high", "low", "close", "volume")
            if col in old.columns and col in current.columns
        ]
        old_values = old.loc[common, columns]
        current_values = current.loc[common, columns]
        equal = old_values.eq(current_values) | (old_values.isna() & current_values.isna())
        changed = ~equal.all(axis=1)
        evidence[ticker] = {
            "baseline_blob": _git_blob(ORIGINAL_UNIVERSE_GIT_REF, relpath),
            "current_sha256": _sha256_file(ROOT / relpath),
            "overlapping_bars": len(common),
            "changed_overlapping_bars": int(changed.sum()),
            "first_changed_date": (
                pd.Timestamp(common[changed][0]).strftime("%Y-%m-%d") if changed.any() else None
            ),
            "last_changed_date": (
                pd.Timestamp(common[changed][-1]).strftime("%Y-%m-%d") if changed.any() else None
            ),
        }
    return evidence


def _event_reconciliation_receipt(
    prior_events: pd.DataFrame,
    rebuilt_events: pd.DataFrame,
    comparison_source: dict[str, Any],
    current_raw_files: list[Path],
) -> dict[str, Any]:
    """Explain every event-key delta against the selected prior generation exactly."""
    keys = ["date", "ticker", "event"]
    prior = prior_events.copy()
    rebuilt = rebuilt_events.copy()
    for frame in (prior, rebuilt):
        frame["date"] = pd.to_datetime(frame["date"])
    prior_duplicate_count = int(prior.duplicated(keys).sum())
    rebuilt_duplicate_count = int(rebuilt.duplicated(keys).sum())
    prior_keys = set(map(tuple, prior[keys].itertuples(index=False, name=None)))
    rebuilt_keys = set(map(tuple, rebuilt[keys].itertuples(index=False, name=None)))
    added_keys = rebuilt_keys - prior_keys
    removed_keys = prior_keys - rebuilt_keys
    added = rebuilt[rebuilt[keys].apply(tuple, axis=1).isin(added_keys)].copy()
    removed = prior[prior[keys].apply(tuple, axis=1).isin(removed_keys)].copy()

    original_tickers = _baseline_universe_tickers()
    current_tickers = {path.stem for path in current_raw_files}
    later_tickers = current_tickers - original_tickers
    broad_gap = rebuilt[
        rebuilt["ticker"].isin(later_tickers)
        & (rebuilt["date"] <= GAP_CENSUS_CUTOFF)
    ].copy()
    broad_gap_keys = set(map(tuple, broad_gap[keys].itertuples(index=False, name=None)))
    gap_overlap = len(prior_keys & broad_gap_keys)

    later_post_gap_added = added[
        added["ticker"].isin(later_tickers)
        & (added["date"] > GAP_CENSUS_CUTOFF)
    ]
    classifier_ticker = {"302132.SZ"}
    raw_delta_tickers = {"000990.SZ", "603663.SS", "300806.SZ", "002827.SZ", "301225.SZ"}
    classifier_added = added[added["ticker"].isin(classifier_ticker)]
    classifier_removed = removed[removed["ticker"].isin(classifier_ticker)]
    raw_delta_added = added[added["ticker"].isin(raw_delta_tickers)]
    raw_delta_removed = removed[removed["ticker"].isin(raw_delta_tickers)]

    # Derive rule-heal reasons from the immutable positive-volume listing clock rather than a
    # hard-coded ticker census. This keeps the receipt independently recomputable as raw files grow.
    from engine.china_microstructure import (
        CHINEXT_STAR_IPO_WINDOW,
        CHINEXT_WIDE_DATE,
        LIMIT_TAPE_START_DATE,
        _infer_listing_date,
        _ipo_no_limit_dates,
        _positive_volume_rows,
    )

    registration_ipo_keys: set[tuple[Any, ...]] = set()
    for ticker in sorted(set(removed["ticker"].astype(str))):
        if _board_from_ticker(ticker) != "main":
            continue
        raw_path = RAW_DIR / f"{ticker}.parquet"
        if not raw_path.exists():
            continue
        raw = pd.read_parquet(raw_path, columns=["close", "volume"])
        traded = _positive_volume_rows(raw)
        no_limit_dates = set(
            _ipo_no_limit_dates(traded, "main", _infer_listing_date(raw))
        )
        ticker_rows = removed[
            (removed["ticker"] == ticker) & removed["date"].isin(no_limit_dates)
        ]
        registration_ipo_keys.update(
            map(tuple, ticker_rows[keys].itertuples(index=False, name=None))
        )
    registration_ipo_removed = removed[
        removed[keys].apply(tuple, axis=1).isin(registration_ipo_keys)
    ]

    pre_reform_chinext_keys: set[tuple[Any, ...]] = set()
    for ticker in sorted(set(added["ticker"].astype(str))):
        if _board_from_ticker(ticker) != "chinext":
            continue
        raw_path = RAW_DIR / f"{ticker}.parquet"
        if not raw_path.exists():
            continue
        raw = pd.read_parquet(raw_path, columns=["close", "volume"])
        traded = _positive_volume_rows(raw)
        listing_date = _infer_listing_date(raw)
        if listing_date is None or listing_date >= CHINEXT_WIDE_DATE:
            continue
        legacy_false_window = {
            pd.Timestamp(ts).normalize() for ts in traded.index[:CHINEXT_STAR_IPO_WINDOW]
        }
        ticker_rows = added[
            (added["ticker"] == ticker) & added["date"].isin(legacy_false_window)
        ]
        pre_reform_chinext_keys.update(
            map(tuple, ticker_rows[keys].itertuples(index=False, name=None))
        )
    pre_reform_chinext_restored = added[
        added[keys].apply(tuple, axis=1).isin(pre_reform_chinext_keys)
    ]
    pre_reform_chinext_original = pre_reform_chinext_restored[
        ~pre_reform_chinext_restored["ticker"].isin(later_tickers)
    ]

    volume_affected_dates: dict[str, set[pd.Timestamp]] = {}
    floor_context_date: dict[str, pd.Timestamp] = {}
    changed_tickers = set(added["ticker"].astype(str)) | set(removed["ticker"].astype(str))
    for ticker in sorted(changed_tickers):
        raw_path = RAW_DIR / f"{ticker}.parquet"
        if not raw_path.exists():
            continue
        raw = pd.read_parquet(raw_path, columns=["volume"])
        raw.index = pd.to_datetime(raw.index)
        raw = raw[~raw.index.isna()].sort_index()
        normalised_index = raw.index.normalize()
        volume = pd.to_numeric(raw["volume"], errors="coerce")
        positive = volume.gt(0)
        affected = set(normalised_index[~positive])
        seen_positive = False
        gap_since_positive = False
        for trade_date, is_positive in zip(normalised_index, positive, strict=True):
            if not is_positive:
                if seen_positive:
                    gap_since_positive = True
                continue
            if gap_since_positive:
                affected.add(pd.Timestamp(trade_date))
            seen_positive = True
            gap_since_positive = False
        volume_affected_dates[ticker] = affected

        positive_dates = normalised_index[positive]
        eligible = positive_dates[positive_dates >= LIMIT_TAPE_START_DATE]
        if len(eligible) and (positive_dates < eligible[0]).any():
            floor_context_date[ticker] = pd.Timestamp(eligible[0])

    def _rows_on_context_dates(
        frame: pd.DataFrame,
        date_map: dict[str, set[pd.Timestamp]],
    ) -> pd.DataFrame:
        mask = [
            row.date in date_map.get(str(row.ticker), set())
            for row in frame[["date", "ticker"]].itertuples(index=False)
        ]
        return frame[pd.Series(mask, index=frame.index)]

    volume_eligibility_added = _rows_on_context_dates(added, volume_affected_dates)
    volume_eligibility_removed = _rows_on_context_dates(removed, volume_affected_dates)
    floor_context_restored = added[
        [
            row.date == floor_context_date.get(str(row.ticker))
            for row in added[["date", "ticker"]].itertuples(index=False)
        ]
    ]

    def _key_set(frame: pd.DataFrame) -> set[tuple[Any, ...]]:
        return set(map(tuple, frame[keys].itertuples(index=False, name=None)))

    pre_reform_keys = _key_set(pre_reform_chinext_restored)
    floor_keys = _key_set(floor_context_restored)
    floor_pre_reform_overlap_keys = floor_keys & pre_reform_keys
    floor_broad_gap_overlap_keys = floor_keys & broad_gap_keys
    floor_context_terminal_keys = floor_keys - pre_reform_keys - broad_gap_keys
    floor_context_terminal = floor_context_restored[
        floor_context_restored[keys].apply(tuple, axis=1).isin(
            floor_context_terminal_keys
        )
    ]
    base_added_reason_keys = _key_set(classifier_added) | _key_set(raw_delta_added)
    base_removed_reason_keys = (
        _key_set(classifier_removed)
        | _key_set(raw_delta_removed)
        | _key_set(registration_ipo_removed)
    )
    positive_volume_original_added = volume_eligibility_added[
        ~volume_eligibility_added["ticker"].isin(later_tickers)
        & ~volume_eligibility_added[keys].apply(tuple, axis=1).isin(
            pre_reform_keys | floor_keys | base_added_reason_keys
        )
    ]
    positive_volume_original_removed = volume_eligibility_removed[
        ~volume_eligibility_removed["ticker"].isin(later_tickers)
        & ~volume_eligibility_removed[keys].apply(tuple, axis=1).isin(
            base_removed_reason_keys
        )
    ]

    # Reasons are descriptive and can legitimately overlap. In this generation, one 300806.SZ
    # event is both a raw-refresh addition and a pre-reform ChiNext restoration; three floor-date
    # events are already present in the broad-gap baseline. Preserve every raw receipt, but assign
    # each key to one arithmetic reason in deterministic precedence order so the terminal ledger
    # is a set union, not a sum of overlapping narratives.
    added_reason_frames = {
        "later_file_events_after_2026_06_30": later_post_gap_added,
        "current_raw_refresh_added": raw_delta_added,
        "classifier_302_chinext_added": classifier_added,
        "pre_reform_chinext_false_ipo_exclusions_restored_original_universe": (
            pre_reform_chinext_original
        ),
        "positive_volume_previous_close_rows_added_original_universe": (
            positive_volume_original_added
        ),
        "start_floor_previous_close_context_rows_restored": floor_context_terminal,
    }
    removed_reason_frames = {
        "stale_prior_rows_removed_after_raw_refresh": raw_delta_removed,
        "old_main_width_rows_removed_by_302_chinext_classifier": classifier_removed,
        "registration_era_main_ipo_no_limit_rows_removed": registration_ipo_removed,
        "positive_volume_ineligible_rows_removed_original_universe": (
            positive_volume_original_removed
        ),
    }

    def _reason_set_receipt(
        reason_frames: dict[str, pd.DataFrame],
        source_frame: pd.DataFrame,
    ) -> tuple[dict[str, int], dict[str, Any]]:
        reason_sets = {name: _key_set(frame) for name, frame in reason_frames.items()}
        assigned: set[tuple[Any, ...]] = set()
        deduplicated_counts: dict[str, int] = {}
        pairwise: dict[str, Any] = {}
        names = list(reason_sets)
        for index, left_name in enumerate(names):
            left = reason_sets[left_name]
            unique = left - assigned
            deduplicated_counts[left_name] = len(unique)
            assigned.update(left)
            for right_name in names[index + 1:]:
                overlap = left & reason_sets[right_name]
                if not overlap:
                    continue
                overlap_rows = source_frame[
                    source_frame[keys].apply(tuple, axis=1).isin(overlap)
                ]
                pairwise[f"{left_name}__AND__{right_name}"] = _event_slice_summary(
                    overlap_rows
                )
        raw_counts = {name: len(reason_set) for name, reason_set in reason_sets.items()}
        return deduplicated_counts, {
            "precedence": names,
            "raw_reason_event_keys": raw_counts,
            "raw_reason_memberships_sum": sum(raw_counts.values()),
            "deduplicated_reason_event_keys": deduplicated_counts,
            "terminal_union_event_keys": len(assigned),
            "duplicate_reason_memberships": sum(raw_counts.values()) - len(assigned),
            "nonzero_pairwise_intersections": pairwise,
        }

    added_deduplicated, added_reason_overlap = _reason_set_receipt(
        added_reason_frames,
        rebuilt,
    )
    removed_deduplicated, removed_reason_overlap = _reason_set_receipt(
        removed_reason_frames,
        prior,
    )

    explained_added_keys = set(map(tuple, pd.concat([
        broad_gap, later_post_gap_added, classifier_added, raw_delta_added,
        pre_reform_chinext_restored, floor_context_restored, volume_eligibility_added,
    ])[keys].itertuples(index=False, name=None)))
    explained_removed_keys = set(map(tuple, pd.concat([
        classifier_removed, raw_delta_removed, registration_ipo_removed,
        volume_eligibility_removed,
    ])[keys].itertuples(index=False, name=None)))
    unexplained_added = len(added_keys - explained_added_keys)
    unexplained_removed = len(removed_keys - explained_removed_keys)

    arithmetic_components = {
        "broad_gap_overlap_already_in_prior": -gap_overlap,
        "later_file_events_after_2026_06_30": added_deduplicated[
            "later_file_events_after_2026_06_30"
        ],
        "current_raw_refresh_added": added_deduplicated["current_raw_refresh_added"],
        "classifier_302_chinext_added": added_deduplicated[
            "classifier_302_chinext_added"
        ],
        "stale_prior_rows_removed_after_raw_refresh": -removed_deduplicated[
            "stale_prior_rows_removed_after_raw_refresh"
        ],
        "old_main_width_rows_removed_by_302_chinext_classifier": -removed_deduplicated[
            "old_main_width_rows_removed_by_302_chinext_classifier"
        ],
        "registration_era_main_ipo_no_limit_rows_removed": -removed_deduplicated[
            "registration_era_main_ipo_no_limit_rows_removed"
        ],
        "pre_reform_chinext_false_ipo_exclusions_restored_original_universe": (
            added_deduplicated[
                "pre_reform_chinext_false_ipo_exclusions_restored_original_universe"
            ]
        ),
        "positive_volume_previous_close_rows_added_original_universe": (
            added_deduplicated[
                "positive_volume_previous_close_rows_added_original_universe"
            ]
        ),
        "positive_volume_ineligible_rows_removed_original_universe": -removed_deduplicated[
            "positive_volume_ineligible_rows_removed_original_universe"
        ],
        "start_floor_previous_close_context_rows_restored": added_deduplicated[
            "start_floor_previous_close_context_rows_restored"
        ],
        "unexplained_added": unexplained_added,
        "unexplained_removed": -unexplained_removed,
    }
    naive_rows = len(prior) + len(broad_gap)
    correction = sum(arithmetic_components.values())
    if naive_rows + correction != len(rebuilt):
        raise RuntimeError(
            "event reconciliation does not close: "
            f"{naive_rows} + {correction} != {len(rebuilt)}"
        )

    shared = prior.merge(rebuilt, on=keys, suffixes=("_prior", "_rebuilt"))
    shared_302 = shared[shared["ticker"] == "302132.SZ"]
    shared_board_relabels = int(
        (shared_302["board_prior"] != shared_302["board_rebuilt"]).sum()
    )
    event_bearing_added = set(rebuilt.loc[rebuilt["ticker"].isin(later_tickers), "ticker"])
    prior_added = set(prior.loc[prior["ticker"].isin(later_tickers), "ticker"])

    return {
        "comparison_source": comparison_source,
        "event_key": keys,
        "prior_rows": len(prior),
        "rebuilt_rows": len(rebuilt),
        "prior_duplicate_event_keys": prior_duplicate_count,
        "rebuilt_duplicate_event_keys": rebuilt_duplicate_count,
        "added_event_keys": len(added_keys),
        "removed_event_keys": len(removed_keys),
        "net_event_keys": len(added_keys) - len(removed_keys),
        "broad_gap_census": {
            "cutoff_inclusive": GAP_CENSUS_CUTOFF.strftime("%Y-%m-%d"),
            "original_raw_files": len(original_tickers),
            "current_raw_files": len(current_tickers),
            "later_added_files": len(later_tickers),
            "rows": len(broad_gap),
            "tickers": int(broad_gap["ticker"].nunique()),
            "rows_already_present_in_prior": gap_overlap,
            "event_bearing_later_tickers_absent_from_prior": len(
                event_bearing_added - prior_added
            ),
            "detail": _event_slice_summary(broad_gap),
        },
        "naive_prior_plus_broad_gap_rows": naive_rows,
        "rebuilt_minus_naive_rows": len(rebuilt) - naive_rows,
        "arithmetic_components": arithmetic_components,
        "reason_overlap_receipt": {
            "added": added_reason_overlap,
            "removed": removed_reason_overlap,
            "floor_context_cross_reason_deduplication": {
                "raw_floor_context_event_keys": len(floor_keys),
                "overlap_with_all_pre_reform_chinext_event_keys": len(
                    floor_pre_reform_overlap_keys
                ),
                "overlap_with_broad_gap_baseline_event_keys": len(
                    floor_broad_gap_overlap_keys
                ),
                "overlap_union_event_keys": len(
                    floor_pre_reform_overlap_keys | floor_broad_gap_overlap_keys
                ),
                "terminal_floor_context_event_keys": len(floor_context_terminal_keys),
                "pre_reform_overlap_detail": _event_slice_summary(
                    rebuilt[
                        rebuilt[keys].apply(tuple, axis=1).isin(
                            floor_pre_reform_overlap_keys
                        )
                    ]
                ),
                "broad_gap_overlap_detail": _event_slice_summary(
                    rebuilt[
                        rebuilt[keys].apply(tuple, axis=1).isin(
                            floor_broad_gap_overlap_keys
                        )
                    ]
                ),
                "precedence": (
                    "broad-gap baseline and pre-reform ChiNext own overlaps before "
                    "floor-context arithmetic"
                ),
            },
            "arithmetic_uses_deduplicated_reason_event_keys": True,
        },
        "added_detail": _event_slice_summary(added),
        "removed_detail": _event_slice_summary(removed),
        "reason_detail": {
            "later_file_post_gap_added": _event_slice_summary(later_post_gap_added),
            "current_raw_refresh_added": _event_slice_summary(raw_delta_added),
            "current_raw_refresh_removed": _event_slice_summary(raw_delta_removed),
            "classifier_302_chinext_added": _event_slice_summary(classifier_added),
            "classifier_302_chinext_removed": _event_slice_summary(classifier_removed),
            "classifier_302_shared_keys_relabelled_main_to_chinext": shared_board_relabels,
            "registration_era_main_ipo_no_limit_removed": _event_slice_summary(
                registration_ipo_removed
            ),
            "pre_reform_chinext_false_ipo_exclusions_restored": _event_slice_summary(
                pre_reform_chinext_restored
            ),
            "positive_volume_previous_close_rows_added": _event_slice_summary(
                positive_volume_original_added
            ),
            "positive_volume_ineligible_rows_removed": _event_slice_summary(
                positive_volume_original_removed
            ),
            "start_floor_previous_close_context_rows_restored": _event_slice_summary(
                floor_context_restored
            ),
        },
        "raw_revision_evidence_vs_original_generation": _raw_revision_evidence(
            raw_delta_tickers
        ),
        "conclusion": (
            "Reconciliation closes exactly with no duplicate keys or residual delta: "
            f"{len(added_keys):,} event keys were added, {len(removed_keys):,} removed, "
            f"including {len(registration_ipo_removed):,} false registration-era main IPO "
            f"no-limit rows removed, {len(pre_reform_chinext_restored):,} pre-reform "
            f"ChiNext rows restored, {len(floor_context_restored):,} floor-boundary rows "
            "restored, and positive-volume eligibility applied."
        ),
    }


def _rule_fix_delta_receipt(
    rebuilt_events: pd.DataFrame,
    rebuilt_tape: pd.DataFrame,
) -> dict[str, Any]:
    """Receipt the bounded rule repair against the registration-only generation exactly."""
    events_path = "data/china_microstructure/limit_events.parquet"
    tape_path = "data/china_microstructure/limit_tape.parquet"
    before_events = pd.read_parquet(
        io.BytesIO(_git_bytes(REGISTRATION_ONLY_COMPARISON_REF, events_path))
    )
    before_tape = pd.read_parquet(
        io.BytesIO(_git_bytes(REGISTRATION_ONLY_COMPARISON_REF, tape_path))
    )
    before_events["date"] = pd.to_datetime(before_events["date"])
    after_events = rebuilt_events.copy()
    after_events["date"] = pd.to_datetime(after_events["date"])
    before_tape["date"] = pd.to_datetime(before_tape["date"])
    after_tape = rebuilt_tape.copy()
    after_tape["date"] = pd.to_datetime(after_tape["date"])

    keys = ["date", "ticker", "event"]
    before_keys = set(map(tuple, before_events[keys].itertuples(index=False, name=None)))
    after_keys = set(map(tuple, after_events[keys].itertuples(index=False, name=None)))
    added_keys = after_keys - before_keys
    removed_keys = before_keys - after_keys
    added = after_events[after_events[keys].apply(tuple, axis=1).isin(added_keys)]
    removed = before_events[before_events[keys].apply(tuple, axis=1).isin(removed_keys)]

    shared = before_events.merge(after_events, on=keys, suffixes=("_before", "_after"))
    attribute_changes: dict[str, int] = {}
    for column in ("board", "limit_width", "lianban_count", "close_off_limit_pct"):
        left = shared[f"{column}_before"]
        right = shared[f"{column}_after"]
        equal = left.eq(right) | (left.isna() & right.isna())
        attribute_changes[column] = int((~equal).sum())

    def _aggregate_sums(frame: pd.DataFrame) -> dict[str, int]:
        return {
            column: int(frame[column].sum())
            for column in (
                "limit_up_count",
                "limit_down_count",
                "sealed_up_close",
                "failed_up_seal_count",
                "lianban_2plus",
            )
        }

    zero_columns = ["limit_up_count", "limit_down_count"]
    before_zero = set(
        before_tape.loc[before_tape[zero_columns].sum(axis=1).eq(0), "date"]
    )
    after_zero = set(after_tape.loc[after_tape[zero_columns].sum(axis=1).eq(0), "date"])
    return {
        "comparison_source": {
            "kind": "git_ref",
            "ref": REGISTRATION_ONLY_COMPARISON_REF,
            "event_blob": _git_blob(REGISTRATION_ONLY_COMPARISON_REF, events_path),
            "tape_blob": _git_blob(REGISTRATION_ONLY_COMPARISON_REF, tape_path),
        },
        "event_key": keys,
        "before_rows": len(before_events),
        "after_rows": len(after_events),
        "added_event_keys": len(added_keys),
        "removed_event_keys": len(removed_keys),
        "net_event_keys": len(added_keys) - len(removed_keys),
        "added_detail": _event_slice_summary(added),
        "removed_detail": _event_slice_summary(removed),
        "shared_event_attribute_changes": attribute_changes,
        "tape_sessions_before": len(before_tape),
        "tape_sessions_after": len(after_tape),
        "aggregate_sums_before": _aggregate_sums(before_tape),
        "aggregate_sums_after": _aggregate_sums(after_tape),
        "zero_event_session_count_before": len(before_zero),
        "zero_event_session_count_after": len(after_zero),
        "zero_event_session_date_set_changed": before_zero != after_zero,
    }


def _board_from_ticker(ticker: str) -> str:
    from engine.china_microstructure import _board_from_ticker as _b
    return _b(ticker)


def _frame_receipt(frame: pd.DataFrame, path: Path) -> dict[str, Any]:
    dates = pd.to_datetime(frame["date"]) if "date" in frame else pd.Series(dtype="datetime64[ns]")
    return {
        "path": str(path.relative_to(ROOT)),
        "rows": int(len(frame)),
        "min_date": dates.min().strftime("%Y-%m-%d") if len(dates) else None,
        "max_date": dates.max().strftime("%Y-%m-%d") if len(dates) else None,
        "schema": [{"name": col, "dtype": str(frame[col].dtype)} for col in frame.columns],
    }


def _st_membership_receipt(source_max_date: str | None) -> dict[str, Any]:
    snapshot_path = ROOT / "data" / "china_st" / "st_snapshot.parquet"
    history_path = ROOT / "data" / "china_st" / "st_history.parquet"
    snapshot = pd.read_parquet(snapshot_path)
    history = pd.read_parquet(history_path)
    snapshot_asofs = sorted(
        pd.to_datetime(snapshot.get("asof"), errors="coerce")
        .dropna()
        .dt.strftime("%Y-%m-%d")
        .unique()
        .tolist()
    )
    history_dates = sorted(
        pd.to_datetime(history.get("date"), errors="coerce")
        .dropna()
        .dt.strftime("%Y-%m-%d")
        .unique()
        .tolist()
    )
    attested_asof = snapshot_asofs[0] if len(snapshot_asofs) == 1 else None
    source_max = pd.Timestamp(source_max_date) if source_max_date else None
    attested = pd.Timestamp(attested_asof) if attested_asof else None
    stale_days = int((source_max - attested).days) if source_max is not None and attested else None
    return {
        "mode": "current_snapshot_proxy_exact_attested_date_only",
        "pit_history_available": False,
        "unknown_membership_uses_ordinary_width_with_alarm": True,
        "snapshot": {
            "path": str(snapshot_path.relative_to(ROOT)),
            "sha256": _sha256_file(snapshot_path),
            "rows": len(snapshot),
            "asof_values": snapshot_asofs,
            "attested_asof": attested_asof,
        },
        "history_store": {
            "path": str(history_path.relative_to(ROOT)),
            "sha256": _sha256_file(history_path),
            "rows": len(history),
            "distinct_dates": history_dates,
            "note": "one cross-section only; not longitudinal PIT membership history",
        },
        "rebuilt_source_max_date": source_max_date,
        "snapshot_stale_for_source_max": bool(stale_days is not None and stale_days > 0),
        "snapshot_stale_days_at_source_max": stale_days,
        "warning": (
            "Risk-warning membership is applied only on the snapshot's exact asof. Unknown "
            "membership on all other dates uses ordinary board width with a stale-data alarm; "
            "historical then-ST identity remains unknown."
        ),
    }


def _reference_session_receipt(
    tape_df: pd.DataFrame,
    previous_tape_dates: set[str],
) -> dict[str, Any]:
    """Prove that the aggregate tape includes zero-event observed trading sessions."""
    reference_path = RAW_DIR / f"{REFERENCE_TICKER}.parquet"
    reference = pd.read_parquet(reference_path, columns=["close"])
    reference_dates = {
        pd.Timestamp(ts).strftime("%Y-%m-%d")
        for ts in pd.to_datetime(reference.index)
        if pd.Timestamp(ts) >= pd.Timestamp("2011-01-01")
    }
    tape_dates = set(pd.to_datetime(tape_df["date"]).dt.strftime("%Y-%m-%d"))
    before_missing = sorted(reference_dates - previous_tape_dates)
    after_missing = sorted(reference_dates - tape_dates)
    if after_missing:
        raise RuntimeError(
            f"aggregate tape omits {len(after_missing)} {REFERENCE_TICKER} sessions: "
            f"{after_missing[:5]}"
        )

    zero_mask = (
        (tape_df["limit_up_count"] == 0)
        & (tape_df["limit_down_count"] == 0)
        & (tape_df["sealed_up_close"] == 0)
        & (tape_df["failed_up_seal_count"] == 0)
    )
    zero_dates = set(pd.to_datetime(tape_df.loc[zero_mask, "date"]).dt.strftime("%Y-%m-%d"))
    return {
        "reference_ticker": REFERENCE_TICKER,
        "reference_session_count": len(reference_dates),
        "previous_tape_missing_reference_session_count": len(before_missing),
        "previous_tape_missing_reference_sessions": before_missing,
        "rebuilt_tape_missing_reference_session_count": 0,
        "zero_event_session_count": int(zero_mask.sum()),
        "newly_restored_zero_event_session_count": len(set(before_missing) & zero_dates),
    }


def _zt_pool_denominator_receipt(raw_files: list[Path]) -> dict[str, Any]:
    """Disclose that the local OHLCV universe is not the full ZT-pool denominator."""
    pool_path = ROOT / "data" / "china_zt_pool" / "pool.parquet"
    if not pool_path.exists():
        return {"available": False, "reason": "pool.parquet missing"}
    try:
        pool = pd.read_parquet(pool_path, columns=["ticker"])
    except Exception as exc:  # noqa: BLE001
        return {"available": False, "reason": f"pool.parquet unreadable: {exc}"}
    pool_names = set(pool["ticker"].dropna().astype(str))
    raw_names = {path.stem for path in raw_files}
    overlap = pool_names & raw_names
    return {
        "available": True,
        "zt_pool_distinct_tickers": len(pool_names),
        "raw_ohlcv_file_count": len(raw_names),
        "overlap_tickers": len(overlap),
        "zt_pool_tickers_without_local_ohlcv": len(pool_names - raw_names),
        "zt_pool_overlap_pct": round(len(overlap) / len(pool_names) * 100, 2) if pool_names else None,
        "warning": (
            "limit_tape breadth denominators are locally observed OHLCV names per session, "
            "not an official all-A-share listing universe"
        ),
    }


def _publish_generation(
    tape_df: pd.DataFrame,
    events_df: pd.DataFrame,
    manifest: dict[str, Any],
) -> dict[str, Any]:
    """Publish artifacts atomically per file, with the manifest replaced last."""
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    token = f"tmp-{os.getpid()}-{uuid.uuid4().hex}"
    tmp_events = OUT_DIR / f".{EVENTS_PATH.name}.{token}"
    tmp_tape = OUT_DIR / f".{TAPE_PATH.name}.{token}"
    tmp_manifest = OUT_DIR / f".{MANIFEST_PATH.name}.{token}"
    tmp_paths = (tmp_events, tmp_tape, tmp_manifest)
    try:
        events_df.to_parquet(tmp_events, index=False, compression="snappy")
        tape_df.to_parquet(tmp_tape, index=False, compression="snappy")

        artifacts = {
            "limit_events": {
                **_frame_receipt(events_df, EVENTS_PATH),
                "sha256": _sha256_file(tmp_events),
            },
            "limit_tape": {
                **_frame_receipt(tape_df, TAPE_PATH),
                "sha256": _sha256_file(tmp_tape),
            },
        }
        manifest["artifacts"] = artifacts
        manifest["build_identity"] = {
            "algorithm": "sha256",
            "value": _build_identity_value(manifest),
            "reproducible_command": manifest["reproducible_command"],
        }
        tmp_manifest.write_text(
            json.dumps(manifest, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )

        for path in tmp_paths:
            with path.open("rb") as fh:
                os.fsync(fh.fileno())
        os.replace(tmp_events, EVENTS_PATH)
        os.replace(tmp_tape, TAPE_PATH)
        os.replace(tmp_manifest, MANIFEST_PATH)  # generation commit marker, always last
        try:
            directory_fd = os.open(OUT_DIR, os.O_RDONLY)
            try:
                os.fsync(directory_fd)
            finally:
                os.close(directory_fd)
        except OSError:
            pass
        return manifest
    finally:
        for path in tmp_paths:
            if path.exists():
                path.unlink()


def run_backfill(
    start_date: pd.Timestamp | None = None,
    dry_run: bool = False,
    comparison_ref: str | None = None,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Run the full backfill and return (tape_df, events_df).  Write to disk unless dry_run."""
    from engine.china_microstructure import (
        LIMIT_TAPE_START_DATE,
        _detect_limit_events,
        _infer_listing_date,
        _load_st_set,
        _positive_volume_rows,
    )

    # Hard floor: §5 contract mandates 2011→; pre-1997 data lacks the 10% limit regime entirely
    floor = LIMIT_TAPE_START_DATE
    if start_date is not None and start_date > floor and not dry_run:
        raise ValueError(
            "partial --start runs are dry-run only; refusing to overwrite completeness artifacts"
        )
    if start_date is None or start_date < floor:
        if start_date is not None and start_date < floor:
            log.warning(
                "--start %s is before the 2011-01-01 floor; advancing to floor",
                start_date.date(),
            )
        start_date = floor
    log.info("Backfill start floor: %s", start_date.date())

    st_set = _load_st_set(ROOT / "data")
    log.info("ST set size: %d tickers", len(st_set))

    raw_files, raw_inventory = raw_universe_inventory(
        RAW_DIR,
        include_content_hash=not dry_run,
    )
    log.info("Universe: %d raw parquet files", len(raw_files))
    prior_events, previous_tape_dates, comparison_source = _load_comparison_artifacts(
        comparison_ref
    )
    market_session_positions, market_session_clock = _observed_market_session_clock(
        raw_files,
        floor=floor,
    )
    log.info(
        "Observed market-session clock: %d sessions (%s to %s)",
        market_session_clock["sessions"],
        market_session_clock["min_date"],
        market_session_clock["max_date"],
    )

    all_events: list[dict] = []
    universe_n_by_date: dict[str, int] = {}   # date → names with ≥1 bar on that date
    ipo_excluded_by_date: dict[str, int] = {}
    unreadable_files: list[dict[str, str]] = []
    empty_files: list[str] = []
    files_scanned = 0
    files_with_eligible_rows = 0

    for i, fp in enumerate(raw_files):
        ticker = fp.stem  # e.g. 000001.SZ
        board  = _board_from_ticker(ticker)
        try:
            df = pd.read_parquet(fp)
        except Exception as exc:  # noqa: BLE001
            log.warning("Cannot read %s: %s", fp, exc)
            unreadable_files.append({"file": fp.name, "error": str(exc)})
            continue
        files_scanned += 1

        if df.empty:
            empty_files.append(fp.name)
            continue

        df.index = pd.to_datetime(df.index)
        listing_date = _infer_listing_date(df)
        df_scan = _positive_volume_rows(df)
        if start_date is not None:
            df_scan = df_scan[df_scan.index >= start_date]

        if df_scan.empty:
            continue
        files_with_eligible_rows += 1

        events, ipo_excluded_dates, _ = _detect_limit_events(
            ticker=ticker,
            df=df,
            board=board,
            st_set=st_set,
            start_date=start_date,
            listing_date=listing_date,
            market_session_positions=market_session_positions,
        )
        all_events.extend(events)

        # Track executable universe presence: positive-volume observations only.
        for ts in df_scan.index:
            d = ts.strftime("%Y-%m-%d")
            universe_n_by_date[d] = universe_n_by_date.get(d, 0) + 1

        # Track the exact excluded listing-session dates returned by the detector.
        for ts in ipo_excluded_dates:
            d = ts.strftime("%Y-%m-%d")
            ipo_excluded_by_date[d] = ipo_excluded_by_date.get(d, 0) + 1

        if (i + 1) % 200 == 0:
            log.info("  processed %d / %d tickers (%d events so far)",
                     i + 1, len(raw_files), len(all_events))

    log.info("Total raw events detected: %d", len(all_events))
    if unreadable_files:
        raise RuntimeError(
            f"full rebuild incomplete: {len(unreadable_files)} / {len(raw_files)} "
            "raw files were unreadable; existing artifacts were not replaced"
        )

    events_df = pd.DataFrame(all_events) if all_events else pd.DataFrame(columns=[
        "date", "ticker", "board", "limit_width", "event", "lianban_count", "close_off_limit_pct"
    ])

    if not events_df.empty:
        events_df["date"] = pd.to_datetime(events_df["date"])
        events_df = events_df.sort_values(["date", "ticker"]).reset_index(drop=True)

    registration_only_events = pd.read_parquet(io.BytesIO(_git_bytes(
        REGISTRATION_ONLY_COMPARISON_REF,
        "data/china_microstructure/limit_events.parquet",
    )))
    market_session_clock["registration_only_generation_audit"] = (
        _lianban_session_clock_audit(
            registration_only_events,
            market_session_positions,
        )
    )
    market_session_clock["rebuilt_generation_audit"] = _lianban_session_clock_audit(
        events_df,
        market_session_positions,
    )
    if market_session_clock["rebuilt_generation_audit"]["attribute_mismatches"]:
        raise RuntimeError(
            "rebuilt lianban attributes do not reconcile to the market-session clock"
        )

    # --- compute aggregate tape ---
    from engine.china_microstructure import aggregate_daily

    # Convert events_df dates to strings for aggregation
    events_for_agg = events_df.copy()
    if not events_for_agg.empty:
        events_for_agg["date"] = events_for_agg["date"].dt.strftime("%Y-%m-%d")

    tape_df = aggregate_daily(
        events_for_agg,
        universe_n_by_date,
        ipo_excluded_by_date,
        backfill=True,
    )
    if not tape_df.empty:
        tape_df["date"] = pd.to_datetime(tape_df["date"])
        tape_df = tape_df.sort_values("date").reset_index(drop=True)

    # --- sanity gates ---
    _run_sanity_gates(tape_df, events_df)

    if dry_run:
        log.info("DRY RUN — not writing to disk")
        return tape_df, events_df

    source_dates = sorted(universe_n_by_date)
    session_receipt = _reference_session_receipt(tape_df, previous_tape_dates)
    reconciliation = _event_reconciliation_receipt(
        prior_events,
        events_df,
        comparison_source,
        raw_files,
    )
    rule_fix_delta = _rule_fix_delta_receipt(events_df, tape_df)
    event_counts = {
        str(key): int(value)
        for key, value in events_df["event"].value_counts().sort_index().items()
    }
    manifest: dict[str, Any] = {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "implementation_version": REBUILD_IMPLEMENTATION_VERSION,
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "complete": files_scanned == len(raw_files) and not unreadable_files,
        "completeness_scope": (
            "current_1842_file_positive_volume_nominal_OHLCV_scan_and_"
            "observed_session_calendar_only"
        ),
        "not_complete_for": [
            "historical PIT ST/risk-warning membership",
            "official all-A-share listing-universe or breadth denominator coverage",
            "exchange-official per-security listing dates; first positive-volume raw row is the listing proxy",
            "recovery of missing or zero-volume observations as executed trades",
            "ZT-pool tickers without local nominal OHLCV history",
            "exchange-official session identity beyond the >=50-name consensus calendar validated against 600519.SS",
        ],
        "authority": "context_only",
        "producer": {
            "source_sha256": {
                "engine/china_microstructure.py": _sha256_file(
                    ROOT / "engine" / "china_microstructure.py"
                ),
                "scripts/backfill_china_limit_tape.py": _sha256_file(Path(__file__)),
            },
            "python": sys.version.split()[0],
            "pandas": pd.__version__,
            "pyarrow": pyarrow.__version__,
            "executable": sys.executable,
        },
        "raw_universe": {
            **raw_inventory,
            "directory": str(RAW_DIR.relative_to(ROOT)),
            "original_baseline_file_count": ORIGINAL_RAW_UNIVERSE_COUNT,
            "later_additions_since_baseline": len(raw_files) - ORIGINAL_RAW_UNIVERSE_COUNT,
        },
        "scan": {
            "files_discovered": len(raw_files),
            "files_scanned": files_scanned,
            "files_with_eligible_rows": files_with_eligible_rows,
            "empty_file_count": len(empty_files),
            "empty_files": empty_files,
            "unreadable_count": len(unreadable_files),
            "unreadable_files": unreadable_files,
        },
        "source_range": {
            "floor": floor.strftime("%Y-%m-%d"),
            "min_observed_session": source_dates[0] if source_dates else None,
            "max_observed_session": source_dates[-1] if source_dates else None,
        },
        "rule_era": {
            "main_normal": {
                "width_pct": 10.0,
                "legacy_ipo_listing_day_special": {
                    "applies_to_listings_before": "2023-04-10",
                    "excluded_sessions_from_listing": 1,
                    "classification": (
                        "listing day had no ordinary +/-10% band; legacy exchange-specific "
                        "issue-price and intraday controls applied"
                    ),
                    "sse_2014_rule_source": (
                        "https://www.sse.com.cn/aboutus/mediacenter/hotandd/"
                        "c/c_20150912_3988761.shtml"
                    ),
                    "szse_2014_rule_source": (
                        "https://www.szse.cn/aboutus/trends/news/t20140613_518480.html"
                    ),
                },
                "registration_era_ipo_no_limit": {
                    "effective_first_listing_date": "2023-04-10",
                    "excluded_sessions_from_listing": 5,
                    "sse_rule_source": (
                        "https://www.sse.com.cn/lawandrules/sselawsrules2025/repeal/"
                        "rules/c/c_20250612_10824490.shtml"
                    ),
                    "szse_rule_source": (
                        "https://docs.static.szse.cn/www/lawrules/rule/allrules/bussiness/"
                        "W020230217564423808793.pdf"
                    ),
                    "effective_date_source": (
                        "https://www.sse.com.cn/aboutus/mediacenter/hotandd/"
                        "c/c_20230404_5719112.shtml"
                    ),
                },
            },
            "main_risk_warning": {
                "before_2026-07-06_width_pct": 5.0,
                "on_or_after_2026-07-06_width_pct": 10.0,
                "effective_date": "2026-07-06",
                "sse_source": (
                    "https://star.sse.com.cn/aboutus/mediacenter/hotandd/"
                    "c/c_20260424_10816474.shtml"
                ),
                "szse_source": (
                    "https://docs.static.szse.cn/www/lawrules/rule/trade/current/"
                    "W020260424690713155663.pdf"
                ),
                "membership_caveat": (
                    "The current membership snapshot is a non-PIT proxy accepted only on its "
                    "exact attested asof; unknown dates use ordinary board width with an alarm"
                ),
            },
            "star": {
                "width_pct": 20.0,
                "first_listing_date": "2019-07-22",
                "ipo_no_limit_sessions": 5,
                "sse_source": (
                    "https://star.sse.com.cn/star/media/news/c/c_20190719_4866789.shtml"
                ),
            },
            "chinext": {
                "before_2020-08-24_width_pct": 10.0,
                "on_or_after_2020-08-24_width_pct": 20.0,
                "registration_reform_first_listing_date": "2020-08-24",
                "pre_reform_ipo_no_limit_sessions": 1,
                "registration_era_ipo_no_limit_sessions": 5,
                "pre_reform_rule_source": (
                    "https://docs.static.szse.cn/www/aboutus/trends/news/"
                    "W020180328462965472234.pdf"
                ),
                "reform_source": (
                    "https://www.szse.cn/www/investor/index/update/t20200807_580310.html"
                ),
                "effective_date_source": (
                    "https://www.szse.cn/aboutus/trends/news/t20200821_580924.html"
                ),
            },
            "bse": {"width_pct": 30.0, "launch_date": "2021-11-15"},
        },
        "market_session_clock": market_session_clock,
        "st_membership": _st_membership_receipt(source_dates[-1] if source_dates else None),
        "event_counts": event_counts,
        "aggregate_session_coverage": session_receipt,
        "denominator_caveats": {
            "zt_pool_vs_raw_ohlcv": _zt_pool_denominator_receipt(raw_files),
        },
        "historical_gap_census": reconciliation["broad_gap_census"],
        "prior_vs_rebuilt_reconciliation": reconciliation,
        "rule_fix_vs_registration_only_generation": rule_fix_delta,
        "reproducible_command": (
            f"{PINNED_PYTHON} scripts/backfill_china_limit_tape.py"
            + (f" --comparison-ref {comparison_ref}" if comparison_ref else "")
        ),
        "publication": {
            "atomicity": "same-directory os.replace per artifact",
            "commit_marker": str(MANIFEST_PATH.relative_to(ROOT)),
            "manifest_published_last": True,
        },
    }
    published = _publish_generation(tape_df, events_df, manifest)
    log.info(
        "published complete generation %s: events=%d tape=%d",
        published["build_identity"]["value"],
        len(events_df),
        len(tape_df),
    )

    return tape_df, events_df


def _run_sanity_gates(tape_df: pd.DataFrame, events_df: pd.DataFrame) -> None:
    """Print and assert sanity checks.  Aborts on failure."""
    log.info("=== SANITY GATES ===")
    errors: list[str] = []

    if tape_df.empty or events_df.empty:
        log.error("GATE FAIL: tape or events is empty — no data produced")
        sys.exit(1)

    tape = tape_df.copy()
    tape["year"] = pd.to_datetime(tape["date"]).dt.year
    tape["ym"]   = pd.to_datetime(tape["date"]).dt.to_period("M")

    events = events_df.copy()
    events["date"] = pd.to_datetime(events["date"])
    events["year"] = events["date"].dt.year
    events["ym"]   = events["date"].dt.to_period("M")

    # --- Gate 1: 2015-06..07 shows elevated limit-down/sealed_down clusters ---
    period_15_06 = pd.Period("2015-06", "M")
    period_15_07 = pd.Period("2015-07", "M")
    period_14_06 = pd.Period("2014-06", "M")

    crisis_sd = tape[tape["ym"].isin([period_15_06, period_15_07])]["limit_down_count"].sum()
    pre_crisis_sd = tape[tape["ym"].isin([period_14_06])]["limit_down_count"].sum()

    log.info("GATE 1 — 2015-06/07 limit_down_count total: %d  |  2014-06 baseline: %d",
             crisis_sd, pre_crisis_sd)

    if crisis_sd < 100:
        errors.append(
            f"GATE 1 FAIL: 2015-06/07 limit_down events too low ({crisis_sd}); "
            "expected elevated cluster from 2015 market crash"
        )
    else:
        log.info("GATE 1 PASS: elevated limit-down in 2015-06/07 confirmed (%d events)", crisis_sd)

    # --- Gate 2: 2014-11..12 shows elevated sealed_up counts (reform/stimulus rally) ---
    period_14_11 = pd.Period("2014-11", "M")
    period_14_12 = pd.Period("2014-12", "M")
    period_13_11 = pd.Period("2013-11", "M")

    rally_su = tape[tape["ym"].isin([period_14_11, period_14_12])]["sealed_up_close"].sum()
    baseline_su = tape[tape["ym"].isin([period_13_11])]["sealed_up_close"].sum()

    log.info("GATE 2 — 2014-11/12 sealed_up total: %d  |  2013-11 baseline: %d",
             rally_su, baseline_su)

    if rally_su < 200:
        errors.append(
            f"GATE 2 FAIL: 2014-11/12 sealed_up too low ({rally_su}); "
            "expected elevated counts from 2014 bull market kickoff"
        )
    else:
        log.info("GATE 2 PASS: elevated sealed_up in 2014-11/12 confirmed (%d events)", rally_su)

    # --- Gate 3: nonzero events every year 2012→ ---
    latest_year = pd.to_datetime(tape["date"]).dt.year.max()
    years_to_check = range(2012, latest_year + 1)
    annual_counts = tape.groupby("year")["limit_up_count"].sum()

    missing_years = []
    for yr in years_to_check:
        if annual_counts.get(yr, 0) == 0:
            missing_years.append(yr)

    log.info("GATE 3 — annual event counts 2012→: %s",
             {yr: int(annual_counts.get(yr, 0)) for yr in years_to_check})

    if missing_years:
        errors.append(f"GATE 3 FAIL: zero events in years {missing_years}")
    else:
        log.info("GATE 3 PASS: nonzero events in every year 2012→%d", latest_year)

    # --- Gate 4: no pre-2011 rows in tape (start-floor enforcement) ---
    min_tape_date = pd.to_datetime(tape["date"]).min()
    FLOOR = pd.Timestamp("2011-01-01")
    log.info("GATE 4 — min(tape.date): %s  (floor: %s)", min_tape_date.date(), FLOOR.date())

    if min_tape_date < FLOOR:
        errors.append(
            f"GATE 4 FAIL: tape contains rows before 2011-01-01 (min={min_tape_date.date()}); "
            "pre-limit-regime fabricated events must not enter the store"
        )
    else:
        log.info("GATE 4 PASS: min(tape.date) >= 2011-01-01 (%s)", min_tape_date.date())

    log.info("=== SANITY GATES COMPLETE ===")

    if errors:
        for e in errors:
            log.error(e)
        sys.exit(1)

    log.info("ALL SANITY GATES PASSED")


def main() -> int:
    ap = argparse.ArgumentParser(description="Backfill A-share limit-state tape from raw OHLCV")
    ap.add_argument("--start", default=None, help="ISO date to start from (e.g. 2015-01-01)")
    ap.add_argument("--dry-run", action="store_true", help="compute but do not write to disk")
    ap.add_argument(
        "--check-manifest",
        action="store_true",
        help="check committed manifest against the current raw-file membership and exit",
    )
    ap.add_argument(
        "--comparison-ref",
        default=None,
        help="git ref containing the exact prior events/tape generation for diff provenance",
    )
    args = ap.parse_args()

    if args.check_manifest:
        defects = validate_completeness_manifest()
        if defects:
            for defect in defects:
                log.error("MANIFEST CHECK FAIL: %s", defect)
            return 1
        log.info("MANIFEST CHECK PASS: raw universe matches complete rebuild receipt")
        return 0

    start_date = pd.Timestamp(args.start) if args.start else None

    tape_df, events_df = run_backfill(
        start_date=start_date,
        dry_run=args.dry_run,
        comparison_ref=args.comparison_ref,
    )
    log.info("Done. tape=%d rows, events=%d rows", len(tape_df), len(events_df))
    return 0


if __name__ == "__main__":
    sys.exit(main())
